kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: testpv  # Same namespace as the app

resources:
  - ../../../common
  - backup-pvc.yml

configMapGenerator:
  - name: k8s-simple-backup-configmap-env
    behavior: merge
    literals:
      - resource_kind=StatefulSet
      - resource_name=testpv

# Remember to provide the secret key in a secure way!
secretGenerator:
  - name: k8s-simple-backup-secret-env
    literals:
      - BORG_PASSPHRASE=DO_NOT_USE_THIS_KEY

patches:
  - target:
      kind: CronJob
      name: k8s-simple-backup-cron-job
      version: v1
      group: batch
    patch: |-
      # Provide the PVC name to back up
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: testpv-pvc
      # Add another persistent volume for the local backup (this is not required for remote backups)
      - op: add
        path: /spec/jobTemplate/spec/template/spec/volumes/-
        value:
          name: backup
          persistentVolumeClaim:
            claimName: testpv-backup-pvc
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /backup
          name: backup