kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: testpv  # Same namespace as the app
nameSuffix: -forget

resources:
  - ../backup

configMapGenerator:
  - name: k8s-simple-backup-configmap-env  # Before applying the -forget suffix
    behavior: merge
    literals:
      - PRUNE=1

patches:
  - target:
      kind: CronJob
      name: k8s-simple-backup-cron-job  # Before applying the -forget suffix
      version: v1
      group: batch
    patch: |-
      - op: remove  # No need to mount the backup volume 
        path: /spec/jobTemplate/spec/template/spec/initContainers/1/volumeMounts/0
      - op: remove  # No need to mount the backup volume
        path: /spec/jobTemplate/spec/template/spec/volumes/0
