kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-simple-backup-configmap-env
data:
  # KUBECTL
  scale_down_timeout: "600"  # Wait up to X seconds for the pods to scale down
  scale_up_timeout: "600"  # Wait up to X seconds for the pods to scale up

  # BACKUP (BORG)
  # BORG_REPO: "/tmp/backup"  # Set this to the actual path/url to the repository
  BORG_PASSPHRASE: "your-secret-key"  # Use a secret instead!
  BACKUP_DIRS: "/data/"  # Mount the volume to /data (or several volumes to subdirectories)
  COMPRESSION: "auto,zstd,3"  # Compression algorithm and level
  # EXCLUDE: "/data/...;/data/..."  # Optionally exclude files from the backup
  # DEBUG: "1"
  # ...

  # PRUNE (BORG)
  PRUNE: "0"  # Keep all backups (it is recommended to run a single prune job periodically per repository)
  KEEP_DAILY: "7"  # Keep the last X daily backups
  KEEP_WEEKLY: "4"  # Keep the last X weekly backups
  KEEP_MONTHLY: "6"  # Keep the last X monthly backups

  # RESTORE (BORG)
  # EXTRACT_TO: "/"  # Must be set to enable restoring. Extract to the root always, as the same filesystem is used
  # ARCHIVE: "ArchiveName"  # Extract the selected archive (choose an archive using something like `borg list`)
  # EXTRACT_WHAT: ""  # Extract the entire backup or a specific directory