---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rustic-k8s-backup-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rustic-k8s-backup-role
rules: # Manage the scale of the deployment/statefulset/daemonset
  - apiGroups: ["apps"]
    resources:
      - deployments/scale
      - statefulsets/scale
      - daemonsets/scale
    verbs:
      - update
      - patch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rustic-k8s-backup-role-binding
subjects:
  - kind: ServiceAccount
    name: rustic-k8s-backup-service-account
roleRef:
  kind: Role
  name: rustic-k8s-backup-role
  apiGroup: rbac.authorization.k8s.io